### ISSUE TITLE
認領翻譯任務 I

### ISSUE THREAD

**Issue by yuaanlin** [yuaanlin/nextjs.tw#9]
在下面留言自己要認領的頁面路徑，例如 `/docs/basic-features/pages`。

- [ ] docs
  - [ ] basic-features
    - [x] built-in-css-support @AndreaFan123 #51 
    - [x] data-fetching
      - [x] client-side @f312213213 #54 
      - [x] get-server-side-props @Danny101201 #46 
      - [x] get-static-paths @Danny101201 #46
      - [x] get-static-props @jubeatt #35 
      - [x] incremental-static-regeneration @jubeatt #49 
      - [x] overview @Danny101201  #46 
    - [x] environment-variables @Chia1104 #57
    - [ ] eslint @AndreaFan123
    - [x] fast-refresh @AndreaFan123 #36
    - [x] font-optimization @dorahs71 #86
    - [x] image-optimization @dorahs71 #66 
    - [x] layouts  @AndreaFan123 #19 
    - [x] pages @yuaanlin #25 
    - [x] script @AndreaFan123 #89
    - [x] static-file-serving @AndreaFan123 #51 
    - [x] supported-browsers-features @AndreaFan123 #19 
    - [x] typescript @AndreaFan123 #36
  - [x] deployment @0xmimiQ #68 
  - [x] faq @0xmimiQ #64 
  - [x] getting-started @kaiyuncheng #58 
  - [x] going-to-production @t7yang #20 
  - [ ] guides
    - [x] building-forms @0xmimiQ #64 
  - [ ] routing
    - [x] dynamic-routes @DoubleLazyZ #69
    - [x] imperatively @f312213213 #55
    - [x] introduction @DoubleLazyZ #34
    - [x] shallow-routing @f312213213 #70
  - [x] testing @warren30815 #50 
  - [ ] upgrading
- [ ] learn
  - [x] foundations
    - [x] about-nextjs
      - [x] index @YONG-LIN-LIANG #24 
      - [x] what-is-nextjs @YONG-LIN-LIANG #28 
    - [x] from-javascript-to-react
      - [x] adding-interactivity-with-state @warren30815 #43 
      - [x] building-ui-with-components @warren30815 #43 
      - [x] continue-learning-react @warren30815 #43 
      - [x] displaying-data-with-props @warren30815 #43 
      - [x] essential-javascript-react @warren30815 #43 
      - [x] getting-started-with-react @warren30815 #43 
      - [x] index @rayatn1011 #17 
      - [x] react-core-concepts @warren30815 #43 
      - [x] updating-ui-with-javascript @warren30815 #43 
    - [x] from-react-to-nextjs
      - [x] getting-started-with-nextjs @Nicolas19921107 #42
      - [x] index @Nicolas19921107 #42
      - [x] next-steps @Nicolas19921107 #42
    - [x] how-nextjs-works
      - [x] buildtime-and-runtime @yenbigbear #48 
      - [x] bundling @YONG-LIN-LIANG #62
      - [x] cdns-and-edge @YONG-LIN-LIANG #63 
      - [x] client-and-server @yenbigbear #48 
      - [x] code-splitting @YONG-LIN-LIANG #90 
      - [x] compiling @Nicolas19921107 #65 
      - [x] development-and-production @Nicolas19921107 #65 
      - [x] index @lucy70381 #47 
      - [x] minifying @justYu2001 #72 
      - [x] next-steps @FoodChain1028 #32 
      - [x] rendering @rudy0628 #50 

若認領後 7 天尚未提交 Pull Request，且未留言告知需要延長時間，認領的頁面會被釋出供其他貢獻者認領。

專有名詞翻譯參考： [國家教育研究院雙語詞彙、學術名詞暨辭書資訊網](https://terms.naer.edu.tw/)

格式及排版參考： [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)

簡體繁體用語對照： [TongWen Dict](https://github.com/tongwentang/tongwen-dict/blob/main/src/word/it.s2t.ts)

**Comment by yuaanlin** [comment]
認領 `/docs/basic-features/pages`

**Comment by DoubleLazyZ** [comment]
認領 `/docs/routing/introduction`

**Comment by dorahs71** [comment]
認領 `/docs/basic-features/image-optimization` & `/docs/basic-features/font-optimization`

**Comment by AndreaFan123** [comment]
認領 
1. /docs/accessibility.mdx
2. /docs/basic-features/layouts.mdx

**Comment by YONG-LIN-LIANG** [comment]
> 認領
> 
> 1. /learn/foundations/about-nextjs
> 2. /learn/foundations/about-nextjs/what-is-nextjs

**Comment by rayatn1011** [comment]
認領 `/learn/foundations/from-javascript-to-react`

**Comment by warren30815** [comment]
認領 `/learn/foundations/from-javascript-to-react` 除已完成的index外的剩下全部

**Comment by Nicolas19921107** [comment]
來認領試寫~
1. /learn/from-react-to-nextjs/getting-started-with-nextjs
2. /learn/from-react-to-nextjs/index
3. /learn/from-react-to-nextjs/next-steps

**Comment by jubeatt** [comment]
認領 `/docs/basic-features/data-fetching/get-static-props`

**Comment by lucy70381** [comment]
認領 /learn/foundations/how-nextjs-works/index
先試寫看看

**Comment by warren30815** [comment]
認領 `/docs/testing`

**Comment by yenbigbear** [comment]
認領 /learn/foundations/how-nextjs-works/buildtime-and-runtime

**Comment by Nicolas19921107** [comment]
認領
 /learn/foundations/how-nextjs-works/development-and-production
 /learn/foundations/how-nextjs-works/compiling

**Comment by jubeatt** [comment]
認領 ` /docs/basic-features/incremental-static-regeneration`

**Comment by yenbigbear** [comment]
認領 /learn/foundations/how-nextjs-works/client-and-server

**Comment by YONG-LIN-LIANG** [comment]
認領

> 1.   /learn/foundations/how-nextjs-works/bundling
> 2.   /learn/foundations/how-nextjs-works/cdns-and-edge

**Comment by f312213213** [comment]
認領：
`/docs/basic-features/data-fetching/client-side`

試寫一頁看看

**Comment by rudy0628** [comment]
認領
`/learn/foundations/how-nextjs-works/rendering`
最近剛好在用 Next.js 寫專案，試寫一次試看看，第一次參與開源

**Comment by f312213213** [comment]
認領 `/docs/routing/shallow-routing` `/docs/routing/imperatively`

**Comment by Chia1104** [comment]
認領 `/docs/basic-features/environment-variables`

**Comment by AndreaFan123** [comment]
認領 
- `/docs/basic-features/eslint.mdx`
- `/docs/basic-features/script.mdx`

**Comment by 0xmimiQ** [comment]
- 認領 `/docs/deployment`
Status: -
PR: -

**Comment by justYu2001** [comment]
- 認領 `learn/foundations/how-nextjs-works/minifying`
  Status: -
  PR: -

**Comment by YONG-LIN-LIANG** [comment]
認領

> 1.   /learn/foundations/how-nextjs-works/code-splitting

**Comment by CJMario89** [comment]
認領 /docs/upgrading
